name: Package

on:
  push:
    branches:
      - latest
  

jobs:
  package:
    name: Build the package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: docker-compose run --rm --user root -T npm install

      - name: Build the project
        run: docker-compose run --rm --user root -T npm run rollup

      - name: Setup the environment
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Pack & Publish
        run: docker-compose run --rm --user root -T npm publish --access=public
