name: Package

on:
  workflow_run:
    workflows: ["Test"]
    branches: [latest]
    types:
      - completed
  push:
    branches:
      - latest
  

jobs:
  package:
    name: Build the package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Install the dependencies
        run: docker-compose run --rm --user root -T npm install

      - name: Build the project
        run: docker-compose run --rm --user root -T npm run build

      - name: Pack & Publish
        run: docker-compose run --rm --user root -T npm publish
